sudo: required #is required to use docker service in travis

language: csharp
mono: none
dotnet: 2.1.103
dist: trusty

install:
  - dotnet restore

script:
  - cd ClientApp && npm install && cd ..
  - dotnet publish --output /app/ --configuration Release
