sudo: required #is required to use docker service in travis

language: csharp
mono: none
dotnet: 2.1.300
dist: trusty

cache:
  directories:
    - "ClientApp/node_modules"

install:
  - dotnet restore

script:
  - npm install --prefix ./ClientApp
  - dotnet publish --output /app/ --configuration Release
