language: csharp
sudo: false
solution: ./Ferrous.sln
dist: trusty

cache:
  directories:
    - ./Ferrous/node_modules

install:
  - "npm install --prefix ./Ferrous"

mono: none
dotnet: 2.1.300-preview1-008174

script:
  - dotnet publish