language: csharp
mono: none
dotnet: 2.1.300
dist: trusty

cache:
  directories:
    - "ClientApp/node_modules"
    - "~/.local/share/NuGet/Cache"

install:
  - dotnet restore
  - npm install --prefix ./ClientApp

script:
  - dotnet publish --configuration Release
