sudo: required #is required to use docker service in travis

language: csharp
mono: none
dotnet: 2.1.0-preview1
dist: trusty

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "No installs necessary" # put your normal pre-testing installs here

script:
  - echo "No tests for now!" # put your normal testing scripts here

after_success:
  - docker --version  # document the version travis is using
  - docker build .
