version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Load Submodules
          command: |
            git submodule update --init --recursive

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Ferrous/ClientApp/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Pull NPM dependencies
          command: |
            cd Ferrous && cd ClientApp && npm install

      - save_cache:
          paths:
            - Ferrous/ClientApp/node_modules
          key: v1-dependencies-{{ checksum "Ferrous/ClientApp/package.json" }}

      - run:
          name: Build application Docker image
          command: |
            docker --version  # document the version travis is using
            docker build .